services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=shop
    ports:
      - "15432:5432"
    volumes:
      - dbDataSave:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d shop || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - backend
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - db
  wiki:
    image: requarks/wiki:canary-2.5.0-dev.409
    restart: unless-stopped
    ports:
      - "8040:8040"
    environment: 
      - DB_TYPE=postgres
      - DB_HOST=db          # host = service name, NOT "admin"
      - DB_PORT=5432
      - DB_USER=admin       # same as db: POSTGRES_USER
      - DB_PASS=${POSTGRES_PASS}   # <- use a value, not DB_PASS_FILE
      - DB_NAME=shop  
    depends_on:
      db:
        condition: service_healthy      # same as db: POSTGRES_DB
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
  grafana:
    image: grafana/grafana
    ports:
      - "3010:3000"
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=supersecret123
  rabbitmq:
    image: rabbitmq:3-management
    container_name: my_rabbitmq
    ports:
      - "5672:5672"                        # RabbitMQ server
      - "15672:15672"                      # RabbitMQ management console
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq  # RabbitMQ data directory
    environment:
      - RABBITMQ_DEFAULT_USER=pibble       # Change this to your desired username
      - RABBITMQ_DEFAULT_PASS=${RMQ_PASS} # Change this to your desired password
  traefik:
    image: traefik:v3.5
    container_name: traefik_reverseProxy
    ports:
      - "81:80"
      - "444:443"
      - "8083:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
    networks:
      - frontend
    restart: unless-stopped
networks:
  frontend:
    external: true
  backend:
    external: true
volumes:
  dbDataSave: