services:
  db:
    container_name: database
    image: mariadb:12.3.1-ubi10-rc
    restart: unless-stopped
    environment:
      - MYSQL_USER=${MARIADB_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASS}
      - MYSQL_PASSWORD=${MARIADB_PASS}
      - MYSQL_DATABASE=gligar
    ports:
      - "3306:3306"
    volumes:
      - dbDataSave:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
    networks:
      - backend
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    restart: unless-stopped
    networks:
      - backend
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cloudbeaver.rule=Host(`cloudbeaver.local`)"
      - "traefik.http.routers.cloudbeaver.entrypoints=web"
      - "traefik.http.services.cloudbeaver.loadbalancer.server.port=8978"
  wiki:
    container_name: wiki-ecom
    image: requarks/wiki:canary-2.5.0-dev.451
    restart: unless-stopped
    ports:
      - "8040:3000"                         # wiki.js default internal port is 3000
    environment: 
      - DB_TYPE=mariadb
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=${MARIADB_ROOT_USER}                      # same as db: Mariadb User
      - DB_PASS=${MARIADB_ROOT_PASS}        # <- use a value, not DB_PASS_FILE
      - DB_NAME=gligar  
    depends_on:
      db:
        condition: service_healthy          # same as db: mariadb
    networks:
      - frontend
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wiki.rule=Host(`wiki.local`)"
      - "traefik.http.routers.wiki.entrypoints=web"
      - "traefik.http.services.wiki.loadbalancer.server.port=3000"
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.local`)"
      - "traefik.http.routers.prometheus.entrypoints=web"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3010:3000"
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=supersecret123
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.local`)"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_message_broker
    ports:
      - "5672:5672"                         # RabbitMQ server
      - "15672:15672"                       # RabbitMQ management console
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq   # RabbitMQ data directory
    environment:
      - RABBITMQ_DEFAULT_USER=pibble        # Change this to your desired username
      - RABBITMQ_DEFAULT_PASS=${RMQ_PASS}   # Change this to your desired password
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.local`)"
      - "traefik.http.routers.rabbitmq.entrypoints=web"
      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"
  traefik:
    image: traefik:v3.6
    container_name: traefik_reverseProxy
    ports:
      - "81:80"
      - "444:443"
      - "8083:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
    networks:
      - frontend
    restart: unless-stopped
networks:
  frontend:
    external: true
  backend:
    external: true
volumes:
  dbDataSave:
  phpmyadmin_data: